(** Generate verified C libraries from Wire codecs via EverParse.

    Given Wire schemas, generates EverParse .3d files and invokes EverParse to
    produce pure C parsers and validators. The output directory contains a
    self-contained C library: [EverParse.h], [<Name>.h], [<Name>.c], and a
    [test.c] that exercises the validators.

    {b Typical usage} ([gen.ml]):
    {[
      let () =
        Wire_c.main ~package:"clcw" [ Wire_c.schema_of_struct Clcw.struct_ ]
    ]}

    With a minimal [dune] that includes the generated rules:
    {v
      (executable (name gen) (modules gen) (libraries clcw wire.c))
      (rule (mode promote) (alias gen)
       (targets dune.inc) (deps gen.exe) (action (run ./gen.exe dune)))
      (include dune.inc)
    v} *)

type schema
(** A schema bundles a name, Wire module, and wire size. *)

val schema_of_struct : Wire.struct_ -> schema
(** [schema_of_struct s] creates a schema from a fixed-size struct. The name,
    module, and wire size are derived from the struct. Raises [Failure] if the
    struct has variable-length fields. *)

val schema : name:string -> module_:Wire.module_ -> wire_size:int -> schema
(** [schema ~name ~module_ ~wire_size] creates a schema with explicit
    parameters. Prefer {!schema_of_struct} when possible. *)

val generate_3d : outdir:string -> schema list -> unit
(** [generate_3d ~outdir schemas] generates [.3d] files from Wire modules. *)

val generate_c : outdir:string -> schema list -> unit
(** [generate_c ~outdir schemas] invokes EverParse on existing [.3d] files to
    produce C parsers and generates [test.c].

    Requires [3d.exe] (EverParse) in PATH. *)

val generate : outdir:string -> schema list -> unit
(** [generate ~outdir schemas] runs both steps: {!generate_3d} then
    {!generate_c}. *)

val main : package:string -> schema list -> unit
(** [main ~package schemas] dispatches based on [Sys.argv]:
    - [3d] runs {!generate_3d}
    - [c] runs {!generate_c}
    - [dune] generates [dune.inc] with build rules, test, and install stanzas
    - otherwise runs {!generate}. *)

(** {1 FFI Code Generation}

    Generate OCaml/C FFI stubs for roundtrip testing and interop with C parsers
    generated by EverParse. *)

val size_of_struct : Wire.struct_ -> int option
(** [size_of_struct s] computes the fixed wire size of struct [s] in bytes.
    Returns [None] if the struct contains variable-length fields. *)

val everparse_name : string -> string
(** [everparse_name name] returns the EverParse-normalized identifier for a
    struct name. EverParse 3D normalizes names that start with two or more
    consecutive uppercase letters by lowercasing the whole name and capitalizing
    only the first letter (e.g., [CLCW] becomes [Clcw], [TMFrame] becomes
    [Tmframe]). Names with standard camelCase are preserved. *)

val ml_type_of : 'a Wire.typ -> string
(** [ml_type_of typ] returns the OCaml type name for a wire type (e.g., ["int"],
    ["int32"], ["int64"]). *)

val to_c_stubs : Wire.struct_ list -> string
(** [to_c_stubs structs] generates a C file with OCaml FFI stubs that call
    EverParse-generated validators. For each struct [Foo], generates:
    - Validation stub [caml_wire_foo_check] calling [Validate] directly

    The generated C code includes the EverParse headers and sources. Compile
    with [-I <schema_dir>] to find them. EverParse identifier normalization is
    handled automatically. *)

val to_ml_stubs : Wire.struct_ list -> string
(** [to_ml_stubs structs] generates OCaml [external] declarations matching the C
    stubs from {!to_c_stubs}. For each struct [Foo], generates:
    {[
      external foo_check : bytes -> bool = "caml_wire_foo_check"
    ]} *)

val to_ml_stub_name : Wire.struct_ -> string
(** [to_ml_stub_name s] returns the OCaml module name for the generated stub
    file (e.g., ["foo"] for struct [Foo]). *)

val to_ml_stub : Wire.struct_ -> string
(** [to_ml_stub s] generates a flat OCaml stub module for a single struct:
    {[
      (* Generated by wire *)
      external check : bytes -> bool = "caml_wire_foo_check"
    ]} *)

val run_everparse : outdir:string -> schema list -> unit
(** [run_everparse ~outdir schemas] invokes EverParse on .3d files in [outdir].
    Requires [3d.exe] in PATH. *)

val has_3d_exe : unit -> bool
(** [has_3d_exe ()] returns [true] if [3d.exe] is available in PATH or
    [~/.local/everparse/bin/]. *)

val ensure_dir : string -> unit
(** [ensure_dir path] creates the directory [path] if it does not exist. *)
