(** Generic differential testing: OCaml codec vs wire-generated C code.

    Each schema needs [c_read] and [c_write] functions (generated by
    {!Wire.to_c_stubs} and {!Wire.to_ml_stub}). All diff logic is generic over
    any record codec. *)

type 'r schema = {
  name : string;
  codec : 'r Wire.Codec.t;
  c_read : string -> string option;
  c_write : string -> string option;
  equal : 'r -> 'r -> bool;
}

let schema ~name ~codec ~c_read ~c_write ~equal =
  { name; codec; c_read; c_write; equal }

type result =
  | Match
  | Both_failed
  | Value_mismatch of string
  | Only_c_ok of string
  | Only_ocaml_ok of string

let c_roundtrip schema buf =
  match schema.c_read buf with
  | None -> None
  | Some fields -> schema.c_write fields

let wire_size schema = Wire.Codec.wire_size schema.codec

let encode_to_string schema v =
  let buf = Bytes.create (wire_size schema) in
  Wire.Codec.encode schema.codec v buf 0;
  Bytes.unsafe_to_string buf

let decode_from_string schema s =
  Wire.Codec.decode schema.codec (Bytes.of_string s) 0

let read schema buf =
  let c_result = c_roundtrip schema buf in
  let buf_too_short = String.length buf < wire_size schema in
  let ocaml_result =
    if String.length buf = 0 || buf_too_short then None
    else Some (decode_from_string schema buf)
  in
  match (c_result, ocaml_result) with
  | Some c_bytes, Some (Ok v) ->
      let ocaml_bytes = encode_to_string schema v in
      if c_bytes = ocaml_bytes then Match
      else Value_mismatch "roundtrip bytes differ"
  | None, Some (Error _) -> Both_failed
  | Some _, Some (Error _) -> Only_c_ok "OCaml decode failed"
  | None, None -> Both_failed
  | Some _, None -> Only_c_ok "OCaml decode returned empty"
  | None, Some _ -> Only_ocaml_ok "C roundtrip failed"

let write schema value =
  let ocaml_bytes = encode_to_string schema value in
  match c_roundtrip schema ocaml_bytes with
  | Some c_bytes ->
      if c_bytes = ocaml_bytes then Match
      else Value_mismatch "C roundtrip bytes differ from OCaml encoding"
  | None -> Only_ocaml_ok "C rejected OCaml-encoded bytes"

let full_roundtrip schema value =
  let ocaml_bytes = encode_to_string schema value in
  match c_roundtrip schema ocaml_bytes with
  | None -> Only_c_ok "C rejected OCaml-encoded bytes"
  | Some c_bytes -> (
      match decode_from_string schema c_bytes with
      | Ok final ->
          if schema.equal value final then Match
          else Value_mismatch "values differ after full roundtrip"
      | Error _ -> Only_c_ok "OCaml rejected C-encoded bytes")

type packed_test = {
  name : string;
  wire_size : int;
  test_read : string -> result;
  test_write : string -> result;
  test_roundtrip : string -> result;
}

let pack (type r) (schema : r schema) =
  let ws = wire_size schema in
  let decode_value buf =
    let padded =
      if String.length buf >= ws then String.sub buf 0 ws
      else
        let b = Bytes.make ws '\000' in
        Bytes.blit_string buf 0 b 0 (String.length buf);
        Bytes.to_string b
    in
    if String.length padded = 0 then None
    else Some (decode_from_string schema padded)
  in
  {
    name = schema.name;
    wire_size = ws;
    test_read = (fun buf -> read schema buf);
    test_write =
      (fun buf ->
        match decode_value buf with
        | Some (Ok v) -> write schema v
        | Some (Error _) -> Both_failed
        | None -> Both_failed);
    test_roundtrip =
      (fun buf ->
        match decode_value buf with
        | Some (Ok v) -> full_roundtrip schema v
        | Some (Error _) -> Both_failed
        | None -> Both_failed);
  }
