(** Generate EverParse .3d files, run EverParse, and generate C/OCaml FFI
    stubs and benchmark loops from the bench schemas.

    Usage: gen_bench_stubs.exe <schema_dir>

    Outputs:
    - <schema_dir>/*.3d         -- EverParse 3D schema files
    - bench_ep_stubs.c          -- C stubs (via Wire.to_c_stubs) + timed loops
    - bench_ep_stubs.ml         -- OCaml externals (via Wire.to_ml_stubs) + loops
    - bench_ep_dispatch.ml      -- dispatch table mapping names to functions *)

let schema_dir =
  if Array.length Sys.argv > 1 then Sys.argv.(1) else "ep_schemas"

let () =
  (* Create schema directory *)
  (try Unix.mkdir schema_dir 0o755
   with Unix.Unix_error (Unix.EEXIST, _, _) -> ());

  let structs = Bench_schemas.all_structs in

  (* Step 1: Generate .3d files *)
  List.iter
    (fun s ->
      let name = Wire.struct_name s in
      let m = Wire.module_ name [ Wire.typedef ~entrypoint:true s ] in
      Wire.to_3d_file (Filename.concat schema_dir (name ^ ".3d")) m)
    structs;

  (* Step 2: Run EverParse *)
  let cmd =
    Printf.sprintf
      "cd %s && for f in *.3d; do ~/.local/everparse/bin/3d.exe --batch \"$f\" \
       || exit 1; done"
      schema_dir
  in
  let ret = Sys.command cmd in
  if ret <> 0 then (
    Printf.eprintf "EverParse failed with code %d\n" ret;
    exit 1);

  (* Step 3: Generate bench_ep_stubs.c
     Start with the library-generated validation stubs, then append
     timed C loops for the pure-C benchmark column. *)
  let oc = open_out "bench_ep_stubs.c" in
  output_string oc (Wire.to_c_stubs structs);
  (* Append timed C loops *)
  let pr fmt = Printf.fprintf oc fmt in
  pr "\n/* ── Timed C benchmark loops ── */\n\n";
  pr "#include <time.h>\n\n";
  pr "static inline int64_t now_ns(void) {\n";
  pr "  struct timespec ts;\n";
  pr "  clock_gettime(CLOCK_MONOTONIC, &ts);\n";
  pr "  return ts.tv_sec * 1000000000LL + ts.tv_nsec;\n";
  pr "}\n\n";
  List.iter
    (fun s ->
      let name = Wire.struct_name s in
      let ep = Wire.everparse_name name in
      let lower = String.lowercase_ascii name in
      pr "CAMLprim value bench_ep_loop_%s(value v_buf, value v_off, value v_n) {\n"
        lower;
      pr "  uint8_t *buf = (uint8_t *)Bytes_val(v_buf) + Int_val(v_off);\n";
      pr "  uint32_t len = caml_string_length(v_buf) - Int_val(v_off);\n";
      pr "  int count = Int_val(v_n);\n";
      pr "  volatile BOOLEAN result;\n";
      pr "  int64_t t0 = now_ns();\n";
      pr "  for (int i = 0; i < count; i++) {\n";
      pr "    result = %sCheck%s(buf, len);\n" ep ep;
      pr "  }\n";
      pr "  (void)result;\n";
      pr "  int64_t t1 = now_ns();\n";
      pr "  return Val_int(t1 - t0);\n";
      pr "}\n\n")
    structs;
  close_out oc;

  (* Step 4: Generate bench_ep_stubs.ml
     Start with the library-generated externals, then append loop externals. *)
  let oc = open_out "bench_ep_stubs.ml" in
  output_string oc (Wire.to_ml_stubs structs);
  let pr fmt = Printf.fprintf oc fmt in
  pr "(* Timed C benchmark loops *)\n\n";
  List.iter
    (fun s ->
      let lower = String.lowercase_ascii (Wire.struct_name s) in
      pr "external %s_loop : bytes -> int -> int -> int = \"bench_ep_loop_%s\"\n\n"
        lower lower)
    structs;
  close_out oc;

  (* Step 5: Generate bench_ep_dispatch.ml *)
  let oc = open_out "bench_ep_dispatch.ml" in
  let pr fmt = Printf.fprintf oc fmt in
  pr "(* Dispatch table — generated by gen_bench_stubs.exe *)\n\n";
  pr "let get_loop name =\n";
  pr "  match name with\n";
  List.iter
    (fun s ->
      let lower = String.lowercase_ascii (Wire.struct_name s) in
      pr "  | %S -> Bench_ep_stubs.%s_loop\n" lower lower)
    structs;
  pr "  | s -> failwith (\"unknown schema: \" ^ s)\n\n";
  pr "let get_check name =\n";
  pr "  match name with\n";
  List.iter
    (fun s ->
      let lower = String.lowercase_ascii (Wire.struct_name s) in
      pr "  | %S -> Bench_ep_stubs.%s_check\n" lower lower)
    structs;
  pr "  | s -> failwith (\"unknown schema: \" ^ s)\n";
  close_out oc;

  Printf.printf "Generated %d schemas in %s/\n" (List.length structs) schema_dir;
  Printf.printf "Generated bench_ep_stubs.c, bench_ep_stubs.ml\n";
  Printf.printf "Generated bench_ep_dispatch.ml\n"
