(** CCSDS space protocol codecs. *)

(** {2 CLCW} *)

type clcw

val clcw_codec : clcw Wire.Codec.t
(** Codec for the 4-byte CLCW bitfield structure. *)

val clcw_struct : Wire.Everparse.Raw.struct_
(** Wire struct descriptor for EverParse code generation. *)

val clcw_size : int
(** Wire size of a CLCW frame in bytes. *)

val clcw_default : clcw
(** Default CLCW value for benchmarks and tests. *)

val clcw_data : int -> bytes array
(** [clcw_data n] generates [n] synthetic CLCW byte buffers. *)

val cw_lockout : int Wire.Field.t
(** Zero-copy field accessor for the CLCW Lockout flag. *)

val cw_wait : int Wire.Field.t
(** Zero-copy field accessor for the CLCW Wait flag. *)

val cw_retransmit : int Wire.Field.t
(** Zero-copy field accessor for the CLCW Retransmit flag. *)

val cw_report : int Wire.Field.t
(** Zero-copy field accessor for the CLCW ReportValue field. *)

val bf_cw_lockout : (int, clcw) Wire.Codec.field
(** Bound field for the CLCW Lockout flag. *)

val bf_cw_wait : (int, clcw) Wire.Codec.field
(** Bound field for the CLCW Wait flag. *)

val bf_cw_retransmit : (int, clcw) Wire.Codec.field
(** Bound field for the CLCW Retransmit flag. *)

val bf_cw_report : (int, clcw) Wire.Codec.field
(** Bound field for the CLCW ReportValue field. *)

(** {2 SpacePacket} *)

type packet

val packet_codec : packet Wire.Codec.t
(** Codec for the 6-byte CCSDS Space Packet primary header. *)

val packet_struct : Wire.Everparse.Raw.struct_
(** Wire struct descriptor for EverParse code generation. *)

val packet_size : int
(** Wire size of a Space Packet header in bytes. *)

val packet_default : packet
(** Default Space Packet value for benchmarks and tests. *)

val f_sp_apid : int Wire.Field.t
(** Zero-copy field accessor for the APID field (11-bit bitfield). *)

val f_sp_seq_count : int Wire.Field.t
(** Zero-copy field accessor for the SeqCount field (14-bit bitfield). *)

val f_sp_data_len : int Wire.Field.t
(** Zero-copy field accessor for the DataLength field. *)

val bf_sp_apid : (int, packet) Wire.Codec.field
(** Bound field for the APID field. *)

val bf_sp_seq_count : (int, packet) Wire.Codec.field
(** Bound field for the SeqCount field. *)

val bf_sp_data_len : (int, packet) Wire.Codec.field
(** Bound field for the DataLength field. *)

val packet_data : int -> bytes array
(** [packet_data n] generates [n] synthetic Space Packet byte buffers. *)

(** {2 FullPacket} *)

type full_packet

val full_packet_codec : full_packet Wire.Codec.t
(** Full Space Packet: 6-byte header + variable-size data payload. Exercises
    [byte_array ~size:Expr.(Field.ref f + int 1)] — CCSDS defines DataLength as
    num_octets_in_data_field minus 1. *)

(** {2 TMFrame} *)

type tm_frame

val tm_frame_codec : tm_frame Wire.Codec.t
(** Codec for the 6-byte TM Transfer Frame primary header. *)

val tm_frame_struct : Wire.Everparse.Raw.struct_
(** Wire struct descriptor for EverParse code generation. *)

val tm_frame_size : int
(** Wire size of a TM Frame header in bytes. *)

val tm_frame_default : tm_frame
(** Default TM Frame value for benchmarks and tests. *)

val f_tf_vcid : int Wire.Field.t
(** Zero-copy field accessor for the VCID field (3-bit bitfield). *)

val f_tf_first_hdr : int Wire.Field.t
(** Zero-copy field accessor for the First Header Pointer (11-bit bitfield). *)

val bf_tf_vcid : (int, tm_frame) Wire.Codec.field
(** Bound field for the VCID field. *)

val bf_tf_first_hdr : (int, tm_frame) Wire.Codec.field
(** Bound field for the First Header Pointer. *)

val tm_frame_data : int -> bytes array
(** [tm_frame_data n] generates [n] synthetic TM Frame byte buffers. *)

(** {2 TMWithOCF} *)

type tm_with_ocf

val tm_with_ocf_codec : tm_with_ocf Wire.Codec.t
(** TM Frame header with optional 4-byte Operational Control Field. Exercises
    [optional Expr.(Field.ref f <> int 0) uint32be] — CCSDS defines the OCF as
    present when OCFFlag == 1. *)

(** {2 Nested protocol} *)

type inner_cmd
type outer_hdr

val inner_cmd_codec : inner_cmd Wire.Codec.t
(** Codec for the 4-byte inner command structure. *)

val inner_cmd_size : int
(** Wire size of an InnerCmd in bytes. *)

val f_cmd_id : int Wire.Field.t
(** Zero-copy field accessor for the InnerCmd CmdId field. *)

val f_cmd_seq : int Wire.Field.t
(** Zero-copy field accessor for the InnerCmd Seq field. *)

val bf_cmd_id : (int, inner_cmd) Wire.Codec.field
(** Bound field for the InnerCmd CmdId field. *)

val bf_cmd_seq : (int, inner_cmd) Wire.Codec.field
(** Bound field for the InnerCmd Seq field. *)

val outer_hdr_codec : outer_hdr Wire.Codec.t
(** [outer_hdr_codec] is the variable-size outer header codec with dependent
    payload length. The Payload field size comes from the runtime value of the
    Length field via [Codec.field_ref]. *)

val outer_hdr_size : int
(** Total size of an OuterHdr with an InnerCmd payload (4 + 4 = 8 bytes). Since
    the codec is variable-size, this is the fixed header size plus the inner
    command size, matching the test data generated by {!nested_data}. *)

val f_oh_length : int Wire.Field.t
(** Zero-copy field accessor for the OuterHdr Length field. *)

val f_oh_payload : Bytesrw.Bytes.Slice.t Wire.Field.t
(** Zero-copy field accessor for the OuterHdr Payload byte slice. *)

val bf_oh_length : (int, outer_hdr) Wire.Codec.field
(** Bound field for the OuterHdr Length field. *)

val bf_oh_payload : (Bytesrw.Bytes.Slice.t, outer_hdr) Wire.Codec.field
(** Bound field for the OuterHdr Payload byte slice. *)

val nested_data : int -> bytes array
(** [nested_data n] generates [n] synthetic nested protocol byte buffers. *)
